export interface RequestToolResult {
	callId: string | null;
	content: string;
	isError: boolean;
}
export interface RequestToolCall {
	id: string | null;
	name: string;
	arguments: string;
	results: RequestToolResult[];
}
export interface RequestToolHistory {
	calls: RequestToolCall[];
	unmatchedResults: RequestToolResult[];
}
const object = (value: unknown): value is Record<string, unknown> => value !== null && typeof value === 'object' && !Array.isArray(value);
const text = (value: unknown): string | null => typeof value === 'string' && value.length ? value : null;
const display = (value: unknown): string => typeof value === 'string' ? value : value === undefined ? '' : JSON.stringify(value, null, 2);

/** Calls carried in input history are distinct from new calls generated by this response. */
export function requestToolHistory(request: unknown): RequestToolHistory {
	const history: RequestToolHistory = { calls: [], unmatchedResults: [] };
	if (!object(request)) return history;
	// One pass over input order. Never attach a result to a later call or pair
	// parallel calls by name; only legacy function messages lack a call ID.
	const byId = new Map<string, RequestToolCall>();
	const legacyByName = new Map<string, RequestToolCall>();
	function call(value: unknown, legacy = false) {
		if (!object(value)) return;
		const fn = object(value.function) ? value.function : object(value.custom) ? value.custom : value;
		const id = text(value.call_id) ?? text(value.id);
		const name = text(fn.name) ?? 'Unnamed tool';
		const entry: RequestToolCall = {
			id, name,
			arguments: display(Object.hasOwn(fn, 'arguments') ? fn.arguments : fn.input),
			results: []
		};
		history.calls.push(entry);
		if (id !== null) byId.set(id, entry);
		else if (legacy) legacyByName.set(name, entry);
	}
	function result(callId: unknown, content: unknown, isError = false, legacyName?: unknown) {
		const id = text(callId);
		const entry: RequestToolResult = { callId: id, content: display(content), isError };
		const owner = id !== null ? byId.get(id) : typeof legacyName === 'string' ? legacyByName.get(legacyName) : undefined;
		if (owner) owner.results.push(entry);
		else history.unmatchedResults.push(entry);
	}
	function item(value: unknown) {
		if (!object(value)) return;
		if (value.type === 'function_call' || value.type === 'custom_tool_call') { call(value); return; }
		if (value.type === 'function_call_output' || value.type === 'custom_tool_call_output') { result(value.call_id, value.output); return; }
		if (Array.isArray(value.tool_calls)) for (const tool of value.tool_calls) call(tool);
		if (value.function_call) call(value.function_call, true);
		if (value.role === 'tool') { result(value.tool_call_id, value.content); return; }
		if (value.role === 'function') { result(null, value.content, false, value.name); return; }
		if (Array.isArray(value.content)) for (const block of value.content) {
			if (!object(block)) continue;
			if (block.type === 'tool_use' || block.type === 'server_tool_use') call(block);
			else if (block.type === 'tool_result' || (typeof block.type === 'string' && block.type.endsWith('_tool_result')))
				result(block.tool_use_id, block.content, block.is_error === true);
		}
	}
	if (Array.isArray(request.messages)) for (const value of request.messages) item(value);
	if (Array.isArray(request.input)) for (const value of request.input) item(value);
	else if (object(request.input)) item(request.input);
	return history;
}
